import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/AuthProvider";
 
 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Radcom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          
          <div className="flex h-screen">
            
            {/* <Sidebar /> */}
            <main className="flex-1">
              {/* <ChatBox /> */}
              {children}
            </main>
          </div>
           
        </AuthProvider>
      </body>
    </html>
  );
}
